// constants.js (v2.0.1)
// SVGをspanキャッシュとして事前生成し、getIconの都度生成コストをゼロに

const SVG_ICONS = {
    repost: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M7 8H16 A3 3 0 0 1 19 11V13M19 13l-1.6-1.6M19 13l1.6-1.6M17 16H8 A3 3 0 0 1 5 13V11M5 11l1.6 1.6M5 11l-1.6 1.6" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
    reply:  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M10 9L6 12l4 3M7 12h7c4 0 6 2 7 6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
    refresh:`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20 12a8 8 0 0 1-13.657 5.657M4 12a8 8 0 0 1 13.657-5.657M18 4v4h-4M6 20v-4h4" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
    pin:    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g transform="rotate(-25 12 12)"><circle cx="12" cy="6.6" r="3.6" fill="#3b82f6" stroke="#1d4ed8" stroke-width="1.6"/><path d="M9.5 9.6h5l-1.1 4.7H10.6L9.5 9.6zM12 14.3 L12 22.2" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></g></svg>`,
    like:   `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M10.94,20.38c.19-.16.39-.31.6-.43,5.1-4.63,8.46-7.7,8.46-11.46,0-2.5-2-4.5-4.5-4.5-1.74,0-3.41.81-4.5,2.09-1.09-1.28-2.76-2.09-4.5-2.09-2.5,0-4.5,2-4.5,4.5,0,3.78,3.4,6.86,8.55,11.53l.39.35Z" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/></svg>`,
    trash:  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M4 7h16M10 11v7M14 11v7M6 7l1 14h10l1-14M9 7V5a1 1 0 0 1 1-1h4a1 1 0 0 1 1-1v2" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
    quote:  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2zM13 8l-3 3 3 3" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
    bookmark:`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
    image:  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3.5" y="5" width="17" height="14" rx="2.5"/><path d="M7.5 14l2.5-2.8 3.2 3.6 2.2-2.4 2.6 2.9"/><path d="M12 4.5v6"/><path d="M9.8 7l2.2-2.2L14.2 7"/></svg>`,
    video:  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><rect x="3.5" y="6" width="12.5" height="12" rx="2.2" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M16 10.2l4.5-2.5v8.6L16 13.8z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg>`
};

// 事前に生成済みのHTML文字列をキャッシュ
const ICON_CACHE = Object.create(null);
for (const [k, v] of Object.entries(SVG_ICONS)) {
    ICON_CACHE[k] = `<span class="svg-icon">${v}</span>`;
}

const translations = {
    ja: {
        nav_home:"ホーム",nav_notifications:"通知",nav_search:"検索",nav_discovery:"みつける",nav_profile:"プロフィール",nav_thread:"スレッド",nav_chat:"チャット",nav_settings:"設定",nav_bookmarks:"ブックマーク",nav_feeds:"フィード",
        add_account:"＋ アカウント追加",logout:"ログアウト",post_placeholder:"今なにしてる？",send:"送信",cancel:"キャンセル",
        login_title:"Aerune ログイン",login_id:"ハンドル名 (handle.bsky.social)",login_pw:"アプリパスワード",login_btn:"ログイン",
        reply_placeholder:"@{0} への返信",quote_placeholder:"@{0} を引用中...",login_failed:"ログインに失敗しました。",post_failed:"投稿に失敗しました。下書きは保持されています。",
        delete_confirm:"このポストを削除しますか？",delete_failed:"削除に失敗しました。",
        follow_me:"フォローされています",following:"フォロー中",mutual:"相互フォロー",send_dm:"✉️ DM",
        chat_placeholder:"メッセージを入力...",
        notif_like:"があなたのポストをいいねしました",notif_repost:"があなたのポストをリポストしました",
        notif_follow:"があなたをフォローしました",notif_mention:"があなたをメンションしました",
        notif_reply:"があなたに返信しました",notif_quote:"があなたのポストを引用しました",
        notif_group_like:"があなたのポストをいいねしました",notif_group_repost:"があなたのポストをリポストしました",
        notif_actor_more:"他{0}人",notif_view_reactions:"反応を見る",notif_detail_like:"いいね: {0}件",notif_detail_repost:"リポスト: {0}件",
        notifications_loading:"通知を読み込み中...",notifications_empty:"通知はありません。",notifications_failed:"通知の読み込みに失敗しました。",notifications_load_more:"さらに通知を読み込む",
        notif_toast_title:"新しい通知",notif_toast_body:"{0}件の未読通知があります",
        search_btn:"検索",search_placeholder:"検索キーワードを入力...",search_mode_posts:"投稿",search_mode_users:"ユーザー",searching:"検索中...",search_enter_keyword:"検索キーワードを入力してください",search_no_posts:"該当する投稿はありません。",search_no_users:"該当するユーザーはありません。",search_failed:"検索に失敗しました。",retry:"再試行",reposted_by:"🔁 {0} がリポスト",logout_confirm:"現在のアカウントからログアウトしますか？",
        profile_reply:"＠ リプライ",
        settings_general:"一般設定",settings_moderation:"モデレーション",
        settings_lang:"言語 / Language",settings_limit:"TLや検索の読み込み件数 (10〜100)",settings_save:"保存",settings_saved:"設定を保存しました",
        lang_ja:"日本語",lang_en:"English","lang_pt-BR":"ポルトガル語（ブラジル）",lang_ar:"アラビア語",
        settings_nsfw:"NSFW画像にぼかしを入れる",settings_mutes:"ミュート中のアカウント",settings_blocks:"ブロック中のアカウント",
        settings_bookmark_tab:"サイドバーにブックマークを表示する",
        settings_time_format:"投稿時刻の表示形式",settings_time_relative:"相対表示（〇分前）",settings_time_absolute:"絶対表示（日時）",
        settings_display:"表示と動作",settings_auto_refresh:"自動更新",settings_restore_scroll:"起動時にスクロール位置を復元",
        settings_image_display_style:"複数画像の表示形式",settings_image_display_grid:"グリッド（2列）",settings_image_display_carousel:"カルーセル（横スクロール）",
        settings_font_size:"文字サイズ",settings_font_small:"小",settings_font_medium:"中",settings_font_large:"大",settings_font_extra_large:"特大",
        settings_mute_words:"TLミュートワード",settings_mute_words_hint:"1行に1語、またはカンマ区切りで入力",
        mute_rules_advanced:"詳細ミュートルール",mute_rule_placeholder:"ワードまたは #タグ",mute_rule_content:"本文",mute_rule_tag:"タグ",mute_rule_both:"本文 + タグ",
        mute_rule_never:"無期限",mute_rule_24h:"24時間",mute_rule_7d:"7日",mute_rule_30d:"30日",mute_rule_expired:"期限切れ",
        mute_rule_exclude_following:"フォロー中は除外",mute_rules_empty:"ミュートルールはありません。",
        mod_subscriptions:"リスト / ラベラー購読",mod_list_uri_placeholder:"at://... またはリストURI",mod_list_mute:"ミュートリスト購読",mod_list_block:"ブロックリスト購読",
        settings_mute_lists:"購読中のミュートリスト",settings_block_lists:"購読中のブロックリスト",settings_labelers:"購読中のラベラー",
        mod_list_mute_done:"ミュートリストを購読しました。",mod_list_block_done:"ブロックリストを購読しました。",
        labeler_handle_placeholder:"ラベラーDIDまたはハンドル",labeler_subscribe:"ラベラー購読",labeler_unsubscribe:"購読解除",labeler_subscribed:"ラベラーを購読しました。",labeler_empty:"購読中のラベラーはありません。",
        settings_accounts:"アカウント",accounts_none:"アカウントがありません",account_current:"使用中",account_switch:"切替",account_remove:"削除",account_remove_confirm:"このアカウントを端末から削除しますか？",
        settings_cache:"キャッシュ管理",settings_clear_cache:"キャッシュを削除（画像・TL・下書き）",cache_clear_confirm:"画像・TL・下書きキャッシュを削除します。ログイン情報と設定は保持されます。",cache_cleared:"キャッシュを削除しました。",cache_cleared_detail:"キャッシュを削除しました（{0}件）。",
        settings_about:"About / ライセンス",about_mit:"Aerune本体はMIT Licenseで配布されています。",
        about_ffmpeg:"macOS arm64の動画圧縮では、LGPL構成のFFmpeg独立実行ファイルをchild_process経由で使用します。",
        timeline_home:"ホームTL",
        timeline_new_posts:"新しい投稿があります",
        draft_restored:"下書きを復元しました",video_select:"動画を追加",video_remove:"動画を削除",video_loading:"動画を読み込み中...",video_ready:"動画を添付中",
        video_mp4_only:"この環境ではMP4動画のみ対応しています。",
        video_probe_failed:"動画情報を読み取れませんでした。別の動画ファイルを選択してください。",
        video_too_large:"動画は100MB以下のMP4にしてください（現在: {0}）。",
        video_too_long:"動画は3分以内にしてください（現在: {0}秒）。",
        video_upload_limit:"動画アップロード上限に達しています: {0}",
        video_uploading:"動画をアップロード中... {0}%",
        video_processing:"動画を処理中...",
        video_compressing:"動画を圧縮中... {0}%",
        video_compress_retry:"動画を再圧縮中... {0}%",
        video_compress_failed:"動画圧縮に失敗しました。",
        video_will_compress:"投稿時にMP4へ圧縮します",
        video_failed:"動画投稿に失敗しました。",
        video_with_images_error:"画像と動画は同時に添付できません。",
        draft_save_failed:"下書き保存に失敗しました。",
        feeds_manage:"フィード管理",feeds_source:"TLソース",feeds_open_manager:"フィードを管理",feeds_saved:"保存済みフィード",feeds_pinned:"ピン留めフィード",
        feeds_discover:"フィードを探す",feeds_suggested:"おすすめフィード",feeds_search:"フィード検索",feeds_search_placeholder:"キーワードでフィードを検索",
        feeds_search_results:"検索結果",feeds_none:"フィードはありません",feeds_saved_empty:"保存済みフィードはありません",feeds_add:"追加",feeds_remove:"削除",
        feeds_pin:"ピン留め",feeds_unpin:"ピン解除",feeds_move_up:"上へ",feeds_move_down:"下へ",feeds_selected:"選択中",feeds_refresh:"再読み込み",
        feeds_loading:"フィードを読み込み中...",feeds_error:"フィードの読み込みに失敗しました",feed_by_author:"by @{0}",feed_like_count:"{0} likes",
        discovery_loading:"候補を探しています...",discovery_empty:"まだ候補がありません。少し時間をおいて更新してください。",discovery_failed:"おすすめの取得に失敗しました。",discovery_not_interested:"興味なし",discovery_reason_follow:"{0}さんと近い関心",discovery_reason_like:"あなたがいいねした{0}さんとつながりがあります",discovery_reason_distant:"少し離れたつながり",discovery_reason_more:"ほか{0}件",discovery_followed:"フォローしました。",
        pinned_post:"固定されたポスト",
        ctx_reply:"返信",ctx_repost:"リポスト",ctx_quote:"引用",ctx_profile:"プロフィールを見る",
        ctx_pin:"固定ポストに設定",ctx_unpin:"固定ポストを解除",
        ctx_follow:"フォロー",ctx_unfollow:"フォロー解除",
        ctx_mute:"ミュート",ctx_unmute:"ミュート解除",
        ctx_block:"ブロック",ctx_unblock:"ブロック解除",
        ctx_bookmark:"ブックマークに追加",ctx_unbookmark:"ブックマークを外す",
        ctx_copy_url:"投稿URLをコピー",ctx_copy_text:"本文をコピー",ctx_translate_deepl:"翻訳（DeepLで開く）",ctx_send_dm:"投稿をDM送信",ctx_report:"投稿を通報",ctx_report_account:"アカウントを通報",
        copied:"コピーしました",dm_recipient_prompt:"送信先のハンドル名またはDIDを入力してください",dm_sent:"DMを送信しました",dm_failed:"DMの送信に失敗しました。",dm_unavailable:"このアカウントにはDMを送信できません。",
        chat_loading:"読み込み中...",chat_empty:"会話はありません。",chat_failed:"チャットの読み込みに失敗しました。",chat_load_more:"さらに読み込む",chat_load_older:"過去のメッセージを読み込む",
        report_title:"通報",report_reason:"理由",report_note:"補足",report_do:"通報",report_success:"通報を送信しました。",report_failed:"通報に失敗しました。",
        report_reason_spam:"スパム",report_reason_violation:"利用規約違反",report_reason_misleading:"誤解を招く内容",report_reason_sexual:"性的コンテンツ",report_reason_rude:"嫌がらせ・暴言",report_reason_other:"その他",
        locallist_title:"ローカルリスト",locallist_open_timeline:"タイムラインで開く",locallist_count:"{0}件",locallist_empty:"ローカルリストに追加したアカウントはありません。",locallist_no_posts:"ローカルリストの投稿はありません。",locallist_open_profile:"プロフィール",locallist_export:"エクスポート",locallist_import:"インポート",locallist_exported:"ローカルリストを書き出しました。",locallist_imported:"{0}件をインポートしました。",locallist_import_failed:"ローカルリストのインポートに失敗しました。",locallist_import_invalid:"有効なローカルリストJSONではありません。",locallist_added_at:"追加: {0}",locallist_add_member:"ローカルリストに追加",locallist_remove:"ローカルリストから削除",locallist_added:"ローカルリストに追加しました。",locallist_removed:"ローカルリストから削除しました。",list_empty:"該当するアカウントはありません。",
        save_image:"💾 画像を保存",action_success:"完了しました",
        stats_posts:"ポスト",stats_following:"フォロー",stats_followers:"フォロワー",
        error_details:"【詳細なエラー理由】",network_check:"ネットワーク制限の可能性があります。ブラウザで原因を確認しますか？",
        post_too_long:"ポストが長すぎます。{0}文字オーバーしています。",
        no_bookmarks:"ブックマークはありません",
        bookmark_failed:"ブックマークの操作に失敗しました。",
        login_empty:"IDとパスワードを入力してください。",
        login_app_pw_req:"Aeruneでのログインには、Bluesky公式で発行した「アプリパスワード」が必要です。\n（通常のログインパスワードは使えません）\n\nブラウザを開いて設定画面へ移動しますか？",
        login_invalid:"ID（ハンドル名）またはパスワードが間違っています。\n入力内容をご確認ください。",
        login_rate_limit:"ログイン試行回数が上限に達しました。\nしばらく時間を置いてから再度お試しください。",
        login_network:"通信エラーが発生しました。\nネットワーク接続を確認してください。",
        login_unknown:"原因を調べるためにブラウザ版を開きますか？"
    },
    en: {
        nav_home:"Home",nav_notifications:"Notifications",nav_search:"Search",nav_discovery:"Discover",nav_profile:"Profile",nav_thread:"Thread",nav_chat:"Chat",nav_settings:"Settings",nav_bookmarks:"Bookmarks",nav_feeds:"Feeds",
        add_account:"+ Add Account",logout:"Logout",post_placeholder:"What's up?",send:"Post",cancel:"Cancel",
        login_title:"Login to Aerune",login_id:"Handle (handle.bsky.social)",login_pw:"App Password",login_btn:"Login",
        reply_placeholder:"Reply to @{0}",quote_placeholder:"Quoting @{0}...",login_failed:"Login failed.",post_failed:"Post failed. Draft is kept.",
        delete_confirm:"Are you sure you want to delete this post?",delete_failed:"Failed to delete.",
        follow_me:"Follows you",following:"Following",mutual:"Mutual",send_dm:"✉️ Message",
        chat_placeholder:"Type a message...",
        notif_like:"liked your post",notif_repost:"reposted your post",
        notif_follow:"followed you",notif_mention:"mentioned you",
        notif_reply:"replied to you",notif_quote:"quoted your post",
        notif_group_like:"liked your post",notif_group_repost:"reposted your post",
        notif_actor_more:"and {0} others",notif_view_reactions:"View reactions",notif_detail_like:"Likes: {0}",notif_detail_repost:"Reposts: {0}",
        notifications_loading:"Loading notifications...",notifications_empty:"No notifications.",notifications_failed:"Failed to load notifications.",notifications_load_more:"Load more notifications",
        notif_toast_title:"New notifications",notif_toast_body:"You have {0} unread notifications",
        search_btn:"Search",search_placeholder:"Enter keyword...",search_mode_posts:"Posts",search_mode_users:"Users",searching:"Searching...",search_enter_keyword:"Enter a keyword to search.",search_no_posts:"No matching posts.",search_no_users:"No matching users.",search_failed:"Search failed.",retry:"Retry",reposted_by:"🔁 Reposted by {0}",logout_confirm:"Are you sure you want to log out of the current account?",
        profile_reply:"@ Reply",
        settings_general:"General",settings_moderation:"Moderation",
        settings_lang:"言語 / Language",settings_limit:"Timeline limit (10-100)",settings_save:"Save",settings_saved:"Settings saved",
        lang_ja:"Japanese",lang_en:"English","lang_pt-BR":"Portuguese (Brazil)",lang_ar:"Arabic",
        settings_nsfw:"Blur NSFW Images",settings_mutes:"Muted Accounts",settings_blocks:"Blocked Accounts",
        settings_bookmark_tab:"Show Bookmarks in sidebar",
        settings_time_format:"Post time display",settings_time_relative:"Relative (X min ago)",settings_time_absolute:"Absolute (date & time)",
        settings_display:"Display and behavior",settings_auto_refresh:"Auto refresh",settings_restore_scroll:"Restore scroll position on launch",
        settings_image_display_style:"Image display style",settings_image_display_grid:"Grid (2 columns)",settings_image_display_carousel:"Carousel (horizontal scroll)",
        settings_font_size:"Text size",settings_font_small:"Small",settings_font_medium:"Medium",settings_font_large:"Large",settings_font_extra_large:"Extra large",
        settings_mute_words:"Timeline muted words",settings_mute_words_hint:"Enter one word per line, or comma-separated",
        mute_rules_advanced:"Advanced mute rules",mute_rule_placeholder:"Word or #tag",mute_rule_content:"Content",mute_rule_tag:"Tag",mute_rule_both:"Content + Tag",
        mute_rule_never:"Never",mute_rule_24h:"24 hours",mute_rule_7d:"7 days",mute_rule_30d:"30 days",mute_rule_expired:"Expired",
        mute_rule_exclude_following:"Exclude following",mute_rules_empty:"No mute rules.",
        mod_subscriptions:"List / Labeler Subscriptions",mod_list_uri_placeholder:"at://... or list URI",mod_list_mute:"Subscribe mute list",mod_list_block:"Subscribe block list",
        settings_mute_lists:"Muted Lists",settings_block_lists:"Blocked Lists",settings_labelers:"Labelers",
        mod_list_mute_done:"Subscribed to mute list.",mod_list_block_done:"Subscribed to block list.",
        labeler_handle_placeholder:"Labeler DID or handle",labeler_subscribe:"Subscribe labeler",labeler_unsubscribe:"Unsubscribe",labeler_subscribed:"Subscribed to labeler.",labeler_empty:"No subscribed labelers.",
        settings_accounts:"Accounts",accounts_none:"No accounts.",account_current:"Current",account_switch:"Switch",account_remove:"Remove",account_remove_confirm:"Remove this account from this device?",
        settings_cache:"Cache management",settings_clear_cache:"Clear cache (images, timeline, drafts)",cache_clear_confirm:"Clear image, timeline, and draft cache. Login sessions and settings will be kept.",cache_cleared:"Cache cleared.",cache_cleared_detail:"Cache cleared ({0} items).",
        settings_about:"About / Licenses",about_mit:"Aerune is distributed under the MIT License.",
        about_ffmpeg:"Video compression on macOS arm64 uses an independent LGPL FFmpeg executable through child_process.",
        timeline_home:"Home Timeline",
        timeline_new_posts:"New posts available",
        draft_restored:"Draft restored",video_select:"Add video",video_remove:"Remove video",video_loading:"Loading video...",video_ready:"Video attached",
        video_mp4_only:"This environment only supports MP4 video.",
        video_probe_failed:"Could not read video metadata. Please choose another video file.",
        video_too_large:"Please use an MP4 video under 100MB (current: {0}).",
        video_too_long:"Videos must be 3 minutes or shorter (current: {0}s).",
        video_upload_limit:"Video upload limit reached: {0}",
        video_uploading:"Uploading video... {0}%",
        video_processing:"Processing video...",
        video_compressing:"Compressing video... {0}%",
        video_compress_retry:"Recompressing video... {0}%",
        video_compress_failed:"Failed to compress video.",
        video_will_compress:"Will compress to MP4 before posting",
        video_failed:"Failed to post video.",
        video_with_images_error:"Images and video cannot be attached at the same time.",
        draft_save_failed:"Failed to save draft.",
        feeds_manage:"Feed Management",feeds_source:"Timeline source",feeds_open_manager:"Manage Feeds",feeds_saved:"Saved Feeds",feeds_pinned:"Pinned Feeds",
        feeds_discover:"Discover Feeds",feeds_suggested:"Suggested Feeds",feeds_search:"Search Feeds",feeds_search_placeholder:"Search feeds by keyword",
        feeds_search_results:"Search Results",feeds_none:"No feeds found",feeds_saved_empty:"No saved feeds",feeds_add:"Add",feeds_remove:"Remove",
        feeds_pin:"Pin",feeds_unpin:"Unpin",feeds_move_up:"Move up",feeds_move_down:"Move down",feeds_selected:"Selected",feeds_refresh:"Reload",
        feeds_loading:"Loading feeds...",feeds_error:"Failed to load feeds",feed_by_author:"by @{0}",feed_like_count:"{0} likes",
        discovery_loading:"Finding recommendations...",discovery_empty:"No recommendations yet. Try refreshing again later.",discovery_failed:"Failed to load recommendations.",discovery_not_interested:"Not interested",discovery_reason_follow:"Shared interests around {0}",discovery_reason_like:"Connected to {0}, whose post you liked",discovery_reason_distant:"A slightly different connection",discovery_reason_more:"and {0} more",discovery_followed:"Followed.",
        pinned_post:"Pinned Post",
        ctx_reply:"Reply",ctx_repost:"Repost",ctx_quote:"Quote",ctx_profile:"View Profile",
        ctx_pin:"Pin Post",ctx_unpin:"Unpin Post",
        ctx_follow:"Follow",ctx_unfollow:"Unfollow",
        ctx_mute:"Mute",ctx_unmute:"Unmute",
        ctx_block:"Block",ctx_unblock:"Unblock",
        ctx_bookmark:"Add to Bookmarks",ctx_unbookmark:"Remove Bookmark",
        ctx_copy_url:"Copy Post URL",ctx_copy_text:"Copy Post Text",ctx_translate_deepl:"Translate (Open in DeepL)",ctx_send_dm:"Send Post by DM",ctx_report:"Report Post",ctx_report_account:"Report Account",
        copied:"Copied",dm_recipient_prompt:"Enter the recipient handle or DID",dm_sent:"DM sent",dm_failed:"Failed to send DM.",dm_unavailable:"You cannot send a DM to this account.",
        chat_loading:"Loading...",chat_empty:"No conversations.",chat_failed:"Failed to load chat.",chat_load_more:"Load more",chat_load_older:"Load older messages",
        report_title:"Report",report_reason:"Reason",report_note:"Notes",report_do:"Report",report_success:"Report submitted.",report_failed:"Failed to submit report.",
        report_reason_spam:"Spam",report_reason_violation:"Rule violation",report_reason_misleading:"Misleading content",report_reason_sexual:"Sexual content",report_reason_rude:"Harassment or abuse",report_reason_other:"Other",
        locallist_title:"Local List",locallist_open_timeline:"Open Timeline",locallist_count:"{0} accounts",locallist_empty:"No accounts in your Local List.",locallist_no_posts:"No posts in your Local List.",locallist_open_profile:"Profile",locallist_export:"Export",locallist_import:"Import",locallist_exported:"Local List exported.",locallist_imported:"Imported {0} accounts.",locallist_import_failed:"Failed to import Local List.",locallist_import_invalid:"This is not a valid Local List JSON file.",locallist_added_at:"Added: {0}",locallist_add_member:"Add to Local List",locallist_remove:"Remove from Local List",locallist_added:"Added to Local List.",locallist_removed:"Removed from Local List.",list_empty:"No matching accounts.",
        save_image:"💾 Save Image",action_success:"Success",
        stats_posts:"Posts",stats_following:"Following",stats_followers:"Followers",
        error_details:"[Error Details]",network_check:"Possible network restriction. Would you like to check in your browser?",
        post_too_long:"Post is too long. It exceeds the limit by {0} characters.",
        no_bookmarks:"No bookmarks found.",
        bookmark_failed:"Failed to process bookmark.",
        login_empty:"Please enter your ID and password.",
        login_app_pw_req:"Aerune requires an 'App Password' generated from the official Bluesky settings.\n(Your regular login password will not work.)\n\nOpen browser to go to the settings page?",
        login_invalid:"Incorrect ID (handle) or password.\nPlease check your input.",
        login_rate_limit:"Rate limit exceeded.\nPlease wait a moment and try again.",
        login_network:"A network error occurred.\nPlease check your connection.",
        login_unknown:"Would you like to open the browser to investigate the cause?"
    }
};

translations['pt-BR'] = {
    nav_home:"Início",nav_notifications:"Notificações",nav_search:"Buscar",nav_discovery:"Descobrir",nav_profile:"Perfil",nav_thread:"Conversa",nav_chat:"Chat",nav_settings:"Ajustes",nav_bookmarks:"Favoritos",nav_feeds:"Feeds",
    add_account:"+ Adicionar conta",logout:"Sair",post_placeholder:"O que está acontecendo?",send:"Publicar",cancel:"Cancelar",
    login_title:"Entrar no Aerune",login_id:"Handle (handle.bsky.social)",login_pw:"Senha de app",login_btn:"Entrar",
    reply_placeholder:"Responder a @{0}",quote_placeholder:"Citando @{0}...",login_failed:"Falha ao entrar.",post_failed:"Falha ao publicar. O rascunho foi mantido.",
    delete_confirm:"Deseja excluir esta publicação?",delete_failed:"Falha ao excluir.",
    follow_me:"Segue você",following:"Seguindo",mutual:"Mútuo",send_dm:"✉️ Mensagem",
    chat_placeholder:"Digite uma mensagem...",
    notif_like:"curtiu sua publicação",notif_repost:"repostou sua publicação",notif_follow:"seguiu você",notif_mention:"mencionou você",notif_reply:"respondeu a você",notif_quote:"citou sua publicação",
    notif_group_like:"curtiram sua publicação",notif_group_repost:"repostaram sua publicação",notif_actor_more:"e mais {0}",notif_view_reactions:"Ver reações",notif_detail_like:"Curtidas: {0}",notif_detail_repost:"Reposts: {0}",
    notifications_loading:"Carregando notificações...",notifications_empty:"Sem notificações.",notifications_failed:"Falha ao carregar notificações.",notifications_load_more:"Carregar mais notificações",
    notif_toast_title:"Novas notificações",notif_toast_body:"Você tem {0} notificações não lidas",
    search_btn:"Buscar",search_placeholder:"Digite uma palavra-chave...",search_mode_posts:"Publicações",search_mode_users:"Usuários",searching:"Buscando...",search_enter_keyword:"Digite uma palavra-chave para buscar.",search_no_posts:"Nenhuma publicação encontrada.",search_no_users:"Nenhum usuário encontrado.",search_failed:"Falha na busca.",retry:"Tentar novamente",reposted_by:"🔁 Repostado por {0}",logout_confirm:"Deseja sair da conta atual?",
    profile_reply:"@ Responder",
    settings_general:"Geral",settings_moderation:"Moderação",settings_lang:"Idioma / Language",settings_limit:"Limite da timeline (10-100)",settings_save:"Salvar",settings_saved:"Ajustes salvos",
    lang_ja:"Japonês",lang_en:"Inglês","lang_pt-BR":"Português (Brasil)",lang_ar:"Árabe",
    settings_nsfw:"Desfocar imagens NSFW",settings_mutes:"Contas silenciadas",settings_blocks:"Contas bloqueadas",settings_bookmark_tab:"Mostrar favoritos na barra lateral",
    settings_time_format:"Formato de hora",settings_time_relative:"Relativo (há X min)",settings_time_absolute:"Absoluto (data e hora)",
    settings_display:"Exibição e comportamento",settings_auto_refresh:"Atualização automática",settings_restore_scroll:"Restaurar posição ao iniciar",
    settings_image_display_style:"Estilo de imagens",settings_image_display_grid:"Grade (2 colunas)",settings_image_display_carousel:"Carrossel (rolagem horizontal)",
    settings_font_size:"Tamanho do texto",settings_font_small:"Pequeno",settings_font_medium:"Médio",settings_font_large:"Grande",settings_font_extra_large:"Extra grande",
    settings_mute_words:"Palavras silenciadas na TL",settings_mute_words_hint:"Uma palavra por linha ou separadas por vírgula",
    mute_rules_advanced:"Regras avançadas de silêncio",mute_rule_placeholder:"Palavra ou #tag",mute_rule_content:"Texto",mute_rule_tag:"Tag",mute_rule_both:"Texto + tag",
    mute_rule_never:"Nunca",mute_rule_24h:"24 horas",mute_rule_7d:"7 dias",mute_rule_30d:"30 dias",mute_rule_expired:"Expirado",mute_rule_exclude_following:"Excluir quem sigo",mute_rules_empty:"Nenhuma regra.",
    mod_subscriptions:"Assinaturas de listas / labelers",mod_list_uri_placeholder:"at://... ou URI da lista",mod_list_mute:"Assinar lista de silêncio",mod_list_block:"Assinar lista de bloqueio",
    settings_mute_lists:"Listas silenciadas",settings_block_lists:"Listas bloqueadas",settings_labelers:"Labelers",mod_list_mute_done:"Lista de silêncio assinada.",mod_list_block_done:"Lista de bloqueio assinada.",
    labeler_handle_placeholder:"DID ou handle do labeler",labeler_subscribe:"Assinar labeler",labeler_unsubscribe:"Cancelar assinatura",labeler_subscribed:"Labeler assinado.",labeler_empty:"Nenhum labeler assinado.",
    settings_accounts:"Contas",accounts_none:"Nenhuma conta.",account_current:"Atual",account_switch:"Trocar",account_remove:"Remover",account_remove_confirm:"Remover esta conta deste dispositivo?",
    settings_cache:"Cache",settings_clear_cache:"Limpar cache (imagens, TL, rascunhos)",cache_clear_confirm:"Limpar cache de imagens, timeline e rascunhos. Login e ajustes serão mantidos.",cache_cleared:"Cache limpo.",cache_cleared_detail:"Cache limpo ({0} itens).",
    settings_about:"Sobre / Licenças",about_mit:"Aerune é distribuído sob a licença MIT.",about_ffmpeg:"A compressão de vídeo no macOS arm64 usa um executável FFmpeg LGPL independente via child_process.",
    timeline_home:"Timeline inicial",timeline_new_posts:"Há novas publicações",
    draft_restored:"Rascunho restaurado",video_select:"Adicionar vídeo",video_remove:"Remover vídeo",video_loading:"Carregando vídeo...",video_ready:"Vídeo anexado",
    video_mp4_only:"Este ambiente aceita apenas vídeos MP4.",video_probe_failed:"Não foi possível ler o vídeo. Escolha outro arquivo.",video_too_large:"Use um MP4 com até 100MB (atual: {0}).",video_too_long:"Vídeos devem ter até 3 minutos (atual: {0}s).",
    video_upload_limit:"Limite de upload de vídeo atingido: {0}",video_uploading:"Enviando vídeo... {0}%",video_processing:"Processando vídeo...",video_compressing:"Comprimindo vídeo... {0}%",video_compress_retry:"Recomprimindo vídeo... {0}%",video_compress_failed:"Falha ao comprimir vídeo.",video_will_compress:"Será comprimido para MP4 antes de publicar",video_failed:"Falha ao publicar vídeo.",video_with_images_error:"Imagens e vídeo não podem ser anexados juntos.",
    draft_save_failed:"Falha ao salvar rascunho.",
    feeds_manage:"Gerenciar feeds",feeds_source:"Fonte da TL",feeds_open_manager:"Gerenciar feeds",feeds_saved:"Feeds salvos",feeds_pinned:"Feeds fixados",feeds_discover:"Descobrir feeds",feeds_suggested:"Feeds sugeridos",feeds_search:"Buscar feeds",feeds_search_placeholder:"Buscar feeds por palavra-chave",feeds_search_results:"Resultados",feeds_none:"Nenhum feed",feeds_saved_empty:"Nenhum feed salvo",feeds_add:"Adicionar",feeds_remove:"Remover",feeds_pin:"Fixar",feeds_unpin:"Desafixar",feeds_move_up:"Para cima",feeds_move_down:"Para baixo",feeds_selected:"Selecionado",feeds_refresh:"Recarregar",feeds_loading:"Carregando feeds...",feeds_error:"Falha ao carregar feeds",feed_by_author:"por @{0}",feed_like_count:"{0} curtidas",
    discovery_loading:"Buscando recomendações...",discovery_empty:"Ainda não há recomendações. Tente atualizar novamente mais tarde.",discovery_failed:"Falha ao carregar recomendações.",discovery_not_interested:"Não tenho interesse",discovery_reason_follow:"Interesses próximos de {0}",discovery_reason_like:"Conectado a {0}, cuja publicação você curtiu",discovery_reason_distant:"Uma conexão um pouco diferente",discovery_reason_more:"e mais {0}",discovery_followed:"Seguido.",
    pinned_post:"Publicação fixada",
    ctx_reply:"Responder",ctx_repost:"Repostar",ctx_quote:"Citar",ctx_profile:"Ver perfil",ctx_pin:"Fixar publicação",ctx_unpin:"Desafixar publicação",ctx_follow:"Seguir",ctx_unfollow:"Deixar de seguir",ctx_mute:"Silenciar",ctx_unmute:"Reativar",ctx_block:"Bloquear",ctx_unblock:"Desbloquear",ctx_bookmark:"Adicionar aos favoritos",ctx_unbookmark:"Remover favorito",ctx_copy_url:"Copiar URL",ctx_copy_text:"Copiar texto",ctx_translate_deepl:"Traduzir (abrir no DeepL)",ctx_send_dm:"Enviar por DM",ctx_report:"Denunciar publicação",ctx_report_account:"Denunciar conta",
    copied:"Copiado",dm_recipient_prompt:"Digite o handle ou DID do destinatário",dm_sent:"DM enviada",dm_failed:"Falha ao enviar DM.",dm_unavailable:"Você não pode enviar DM para esta conta.",
    chat_loading:"Carregando...",chat_empty:"Sem conversas.",chat_failed:"Falha ao carregar chat.",chat_load_more:"Carregar mais",chat_load_older:"Carregar anteriores",
    report_title:"Denunciar",report_reason:"Motivo",report_note:"Observações",report_do:"Denunciar",report_success:"Denúncia enviada.",report_failed:"Falha ao enviar denúncia.",
    report_reason_spam:"Spam",report_reason_violation:"Violação de regras",report_reason_misleading:"Conteúdo enganoso",report_reason_sexual:"Conteúdo sexual",report_reason_rude:"Assédio ou abuso",report_reason_other:"Outro",
    locallist_title:"Lista local",locallist_open_timeline:"Abrir timeline",locallist_count:"{0} contas",locallist_empty:"Nenhuma conta na lista local.",locallist_no_posts:"Nenhuma publicação na lista local.",locallist_open_profile:"Perfil",locallist_export:"Exportar",locallist_import:"Importar",locallist_exported:"Lista local exportada.",locallist_imported:"{0} contas importadas.",locallist_import_failed:"Falha ao importar a lista local.",locallist_import_invalid:"Este não é um JSON de lista local válido.",locallist_added_at:"Adicionado: {0}",locallist_add_member:"Adicionar à lista local",locallist_remove:"Remover da lista local",locallist_added:"Adicionado à lista local.",locallist_removed:"Removido da lista local.",list_empty:"Nenhuma conta encontrada.",
    save_image:"💾 Salvar imagem",action_success:"Concluído",stats_posts:"Publicações",stats_following:"Seguindo",stats_followers:"Seguidores",
    error_details:"[Detalhes do erro]",network_check:"Possível restrição de rede. Deseja verificar no navegador?",post_too_long:"A publicação é longa demais. Excede {0} caracteres.",no_bookmarks:"Nenhum favorito encontrado.",bookmark_failed:"Falha ao processar favorito.",
    login_empty:"Digite ID e senha.",login_app_pw_req:"Aerune exige uma senha de app gerada nas configurações oficiais do Bluesky.\n(Sua senha normal não funciona.)\n\nAbrir o navegador para as configurações?",login_invalid:"ID (handle) ou senha incorretos.\nVerifique os dados.",login_rate_limit:"Limite de tentativas excedido.\nTente novamente mais tarde.",login_network:"Erro de rede.\nVerifique sua conexão.",login_unknown:"Deseja abrir o navegador para investigar?"
};

translations.ar = {
    nav_home:"الرئيسية",nav_notifications:"الإشعارات",nav_search:"بحث",nav_discovery:"اكتشف",nav_profile:"الملف الشخصي",nav_thread:"المحادثة",nav_chat:"الدردشة",nav_settings:"الإعدادات",nav_bookmarks:"الإشارات المرجعية",nav_feeds:"الخلاصات",
    add_account:"+ إضافة حساب",logout:"تسجيل الخروج",post_placeholder:"ماذا يحدث؟",send:"نشر",cancel:"إلغاء",
    login_title:"تسجيل الدخول إلى Aerune",login_id:"المعرّف (handle.bsky.social)",login_pw:"كلمة مرور التطبيق",login_btn:"دخول",
    reply_placeholder:"رد على @{0}",quote_placeholder:"اقتباس @{0}...",login_failed:"فشل تسجيل الدخول.",post_failed:"فشل النشر. تم الاحتفاظ بالمسودة.",
    delete_confirm:"هل تريد حذف هذا المنشور؟",delete_failed:"فشل الحذف.",
    follow_me:"يتابعك",following:"تتابعه",mutual:"متابعة متبادلة",send_dm:"✉️ رسالة",
    chat_placeholder:"اكتب رسالة...",
    notif_like:"أعجب بمنشورك",notif_repost:"أعاد نشر منشورك",notif_follow:"تابعك",notif_mention:"ذكرك",notif_reply:"رد عليك",notif_quote:"اقتبس منشورك",
    notif_group_like:"أعجبوا بمنشورك",notif_group_repost:"أعادوا نشر منشورك",notif_actor_more:"و {0} آخرين",notif_view_reactions:"عرض التفاعلات",notif_detail_like:"الإعجابات: {0}",notif_detail_repost:"إعادات النشر: {0}",
    notifications_loading:"جار تحميل الإشعارات...",notifications_empty:"لا توجد إشعارات.",notifications_failed:"فشل تحميل الإشعارات.",notifications_load_more:"تحميل المزيد من الإشعارات",
    notif_toast_title:"إشعارات جديدة",notif_toast_body:"لديك {0} إشعارات غير مقروءة",
    search_btn:"بحث",search_placeholder:"أدخل كلمة بحث...",search_mode_posts:"منشورات",search_mode_users:"مستخدمون",searching:"جار البحث...",search_enter_keyword:"أدخل كلمة للبحث.",search_no_posts:"لا توجد منشورات مطابقة.",search_no_users:"لا يوجد مستخدمون مطابقون.",search_failed:"فشل البحث.",retry:"إعادة المحاولة",reposted_by:"🔁 أعاد {0} النشر",logout_confirm:"هل تريد تسجيل الخروج من الحساب الحالي؟",
    profile_reply:"@ رد",
    settings_general:"عام",settings_moderation:"الإشراف",settings_lang:"اللغة / Language",settings_limit:"حد الخط الزمني (10-100)",settings_save:"حفظ",settings_saved:"تم حفظ الإعدادات",
    lang_ja:"اليابانية",lang_en:"الإنجليزية","lang_pt-BR":"البرتغالية (البرازيل)",lang_ar:"العربية",
    settings_nsfw:"تمويه صور NSFW",settings_mutes:"الحسابات المكتومة",settings_blocks:"الحسابات المحظورة",settings_bookmark_tab:"إظهار الإشارات المرجعية في الشريط الجانبي",
    settings_time_format:"تنسيق وقت المنشور",settings_time_relative:"نسبي (قبل X دقيقة)",settings_time_absolute:"مطلق (التاريخ والوقت)",
    settings_display:"العرض والسلوك",settings_auto_refresh:"تحديث تلقائي",settings_restore_scroll:"استعادة موضع التمرير عند التشغيل",
    settings_image_display_style:"نمط عرض الصور",settings_image_display_grid:"شبكة (عمودان)",settings_image_display_carousel:"عرض أفقي",
    settings_font_size:"حجم النص",settings_font_small:"صغير",settings_font_medium:"متوسط",settings_font_large:"كبير",settings_font_extra_large:"كبير جدًا",
    settings_mute_words:"كلمات مكتومة في الخط الزمني",settings_mute_words_hint:"كلمة في كل سطر أو مفصولة بفواصل",
    mute_rules_advanced:"قواعد كتم متقدمة",mute_rule_placeholder:"كلمة أو #وسم",mute_rule_content:"النص",mute_rule_tag:"الوسم",mute_rule_both:"النص + الوسم",
    mute_rule_never:"بلا انتهاء",mute_rule_24h:"24 ساعة",mute_rule_7d:"7 أيام",mute_rule_30d:"30 يومًا",mute_rule_expired:"منتهية",mute_rule_exclude_following:"استثناء من أتابعهم",mute_rules_empty:"لا توجد قواعد كتم.",
    mod_subscriptions:"اشتراكات القوائم / المصنفين",mod_list_uri_placeholder:"at://... أو URI القائمة",mod_list_mute:"اشترك في قائمة كتم",mod_list_block:"اشترك في قائمة حظر",
    settings_mute_lists:"قوائم الكتم",settings_block_lists:"قوائم الحظر",settings_labelers:"المصنفون",mod_list_mute_done:"تم الاشتراك في قائمة الكتم.",mod_list_block_done:"تم الاشتراك في قائمة الحظر.",
    labeler_handle_placeholder:"DID أو معرّف المصنف",labeler_subscribe:"اشترك في المصنف",labeler_unsubscribe:"إلغاء الاشتراك",labeler_subscribed:"تم الاشتراك في المصنف.",labeler_empty:"لا توجد اشتراكات في المصنفين.",
    settings_accounts:"الحسابات",accounts_none:"لا توجد حسابات.",account_current:"الحالي",account_switch:"تبديل",account_remove:"إزالة",account_remove_confirm:"هل تريد إزالة هذا الحساب من هذا الجهاز؟",
    settings_cache:"التخزين المؤقت",settings_clear_cache:"مسح التخزين المؤقت (الصور والخط الزمني والمسودات)",cache_clear_confirm:"سيتم مسح تخزين الصور والخط الزمني والمسودات. سيتم الاحتفاظ بتسجيل الدخول والإعدادات.",cache_cleared:"تم مسح التخزين المؤقت.",cache_cleared_detail:"تم مسح التخزين المؤقت ({0} عناصر).",
    settings_about:"حول / التراخيص",about_mit:"يتم توزيع Aerune بموجب رخصة MIT.",about_ffmpeg:"ضغط الفيديو على macOS arm64 يستخدم ملف FFmpeg مستقلًا بترخيص LGPL عبر child_process.",
    timeline_home:"الخط الزمني الرئيسي",timeline_new_posts:"توجد منشورات جديدة",
    draft_restored:"تمت استعادة المسودة",video_select:"إضافة فيديو",video_remove:"إزالة الفيديو",video_loading:"جار تحميل الفيديو...",video_ready:"تم إرفاق الفيديو",
    video_mp4_only:"هذه البيئة تدعم فيديو MP4 فقط.",video_probe_failed:"تعذرت قراءة معلومات الفيديو. اختر ملفًا آخر.",video_too_large:"استخدم فيديو MP4 أقل من 100MB (الحالي: {0}).",video_too_long:"يجب أن تكون مدة الفيديو 3 دقائق أو أقل (الحالي: {0} ثانية).",
    video_upload_limit:"تم بلوغ حد رفع الفيديو: {0}",video_uploading:"جار رفع الفيديو... {0}%",video_processing:"جار معالجة الفيديو...",video_compressing:"جار ضغط الفيديو... {0}%",video_compress_retry:"إعادة ضغط الفيديو... {0}%",video_compress_failed:"فشل ضغط الفيديو.",video_will_compress:"سيتم ضغطه إلى MP4 قبل النشر",video_failed:"فشل نشر الفيديو.",video_with_images_error:"لا يمكن إرفاق الصور والفيديو معًا.",
    draft_save_failed:"فشل حفظ المسودة.",
    feeds_manage:"إدارة الخلاصات",feeds_source:"مصدر الخط الزمني",feeds_open_manager:"إدارة الخلاصات",feeds_saved:"الخلاصات المحفوظة",feeds_pinned:"الخلاصات المثبتة",feeds_discover:"اكتشاف الخلاصات",feeds_suggested:"خلاصات مقترحة",feeds_search:"بحث في الخلاصات",feeds_search_placeholder:"ابحث عن خلاصات بكلمة",feeds_search_results:"النتائج",feeds_none:"لا توجد خلاصات",feeds_saved_empty:"لا توجد خلاصات محفوظة",feeds_add:"إضافة",feeds_remove:"إزالة",feeds_pin:"تثبيت",feeds_unpin:"إلغاء التثبيت",feeds_move_up:"لأعلى",feeds_move_down:"لأسفل",feeds_selected:"محدد",feeds_refresh:"إعادة تحميل",feeds_loading:"جار تحميل الخلاصات...",feeds_error:"فشل تحميل الخلاصات",feed_by_author:"بواسطة @{0}",feed_like_count:"{0} إعجاب",
    discovery_loading:"جار البحث عن توصيات...",discovery_empty:"لا توجد توصيات بعد. حاول التحديث لاحقًا.",discovery_failed:"فشل تحميل التوصيات.",discovery_not_interested:"غير مهتم",discovery_reason_follow:"اهتمامات قريبة من {0}",discovery_reason_like:"مرتبط بـ {0} الذي أعجبك منشوره",discovery_reason_distant:"صلة مختلفة قليلًا",discovery_reason_more:"و{0} أخرى",discovery_followed:"تمت المتابعة.",
    pinned_post:"منشور مثبت",
    ctx_reply:"رد",ctx_repost:"إعادة نشر",ctx_quote:"اقتباس",ctx_profile:"عرض الملف",ctx_pin:"تثبيت المنشور",ctx_unpin:"إلغاء تثبيت المنشور",ctx_follow:"متابعة",ctx_unfollow:"إلغاء المتابعة",ctx_mute:"كتم",ctx_unmute:"إلغاء الكتم",ctx_block:"حظر",ctx_unblock:"إلغاء الحظر",ctx_bookmark:"إضافة إلى الإشارات المرجعية",ctx_unbookmark:"إزالة الإشارة المرجعية",ctx_copy_url:"نسخ الرابط",ctx_copy_text:"نسخ النص",ctx_translate_deepl:"ترجمة (فتح في DeepL)",ctx_send_dm:"إرسال عبر رسالة",ctx_report:"الإبلاغ عن المنشور",ctx_report_account:"الإبلاغ عن الحساب",
    copied:"تم النسخ",dm_recipient_prompt:"أدخل معرّف أو DID المستلم",dm_sent:"تم إرسال الرسالة",dm_failed:"فشل إرسال الرسالة.",dm_unavailable:"لا يمكنك إرسال رسالة إلى هذا الحساب.",
    chat_loading:"جار التحميل...",chat_empty:"لا توجد محادثات.",chat_failed:"فشل تحميل الدردشة.",chat_load_more:"تحميل المزيد",chat_load_older:"تحميل الأقدم",
    report_title:"إبلاغ",report_reason:"السبب",report_note:"ملاحظات",report_do:"إبلاغ",report_success:"تم إرسال البلاغ.",report_failed:"فشل إرسال البلاغ.",
    report_reason_spam:"رسائل مزعجة",report_reason_violation:"انتهاك القواعد",report_reason_misleading:"محتوى مضلل",report_reason_sexual:"محتوى جنسي",report_reason_rude:"تحرش أو إساءة",report_reason_other:"أخرى",
    locallist_title:"القائمة المحلية",locallist_open_timeline:"فتح الخط الزمني",locallist_count:"{0} حساب",locallist_empty:"لا توجد حسابات في القائمة المحلية.",locallist_no_posts:"لا توجد منشورات في القائمة المحلية.",locallist_open_profile:"الملف",locallist_export:"تصدير",locallist_import:"استيراد",locallist_exported:"تم تصدير القائمة المحلية.",locallist_imported:"تم استيراد {0} حساب.",locallist_import_failed:"فشل استيراد القائمة المحلية.",locallist_import_invalid:"هذا ليس ملف JSON صالحًا للقائمة المحلية.",locallist_added_at:"أضيف: {0}",locallist_add_member:"إضافة إلى القائمة المحلية",locallist_remove:"إزالة من القائمة المحلية",locallist_added:"تمت الإضافة إلى القائمة المحلية.",locallist_removed:"تمت الإزالة من القائمة المحلية.",list_empty:"لا توجد حسابات مطابقة.",
    save_image:"💾 حفظ الصورة",action_success:"تم",stats_posts:"المنشورات",stats_following:"يتابع",stats_followers:"المتابعون",
    error_details:"[تفاصيل الخطأ]",network_check:"قد توجد قيود شبكة. هل تريد التحقق في المتصفح؟",post_too_long:"المنشور طويل جدًا. يتجاوز الحد بـ {0} حرفًا.",no_bookmarks:"لا توجد إشارات مرجعية.",bookmark_failed:"فشل تنفيذ الإشارة المرجعية.",
    login_empty:"أدخل المعرّف وكلمة المرور.",login_app_pw_req:"يتطلب Aerune كلمة مرور تطبيق من إعدادات Bluesky الرسمية.\n(كلمة المرور العادية لن تعمل.)\n\nهل تريد فتح المتصفح للإعدادات؟",login_invalid:"المعرّف أو كلمة المرور غير صحيحة.\nتحقق من الإدخال.",login_rate_limit:"تم تجاوز حد المحاولات.\nانتظر قليلًا ثم حاول مرة أخرى.",login_network:"حدث خطأ في الشبكة.\nتحقق من الاتصال.",login_unknown:"هل تريد فتح المتصفح للتحقق؟"
};

module.exports = { SVG_ICONS, ICON_CACHE, translations };
