name: Build Apps

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      # 証明書（p12）をインポートするためのキーチェーン作成（Macのみ）
      - name: Install Apple Certificate
        if: matrix.os == 'macos-latest'
        run: |
          security create-keychain -p "" build.keychain
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          echo "${{ secrets.CSC_LINK }}" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "${{ secrets.CSC_KEY_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
          rm certificate.p12

      # API Keyのデコード（Macのみ）
      - name: Prepare Apple API Key
        if: matrix.os == 'macos-latest'
        run: |
          echo "${{ secrets.APPLE_API_KEY }}" | base64 --decode > ${{ github.workspace }}/AuthKey.p8
          chmod 600 ${{ github.workspace }}/AuthKey.p8
          head -n 1 ${{ github.workspace }}/AuthKey.p8
# ビルドと公証
      - name: Build App
        run: npx electron-builder --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          
          # カスタムスクリプト用の変数
          MY_APPLE_API_KEY: ${{ github.workspace }}/AuthKey.p8
          MY_APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          MY_APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          MY_APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          
          DEBUG: electron-builder,electron-notarize,macos-sign
          CSC_IDENTITY_AUTO_DISCOVERY: ${{ matrix.os == 'macos-latest' && 'true' || 'false' }}
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Aerune-Build-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip
            dist/*.AppImage
            dist/latest*.yml
          if-no-files-found: ignore

      - name: Upload to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
